<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-76PGCCB3" name="com.pulse.Test.ValidLogin1" tests="6" failures="1" timestamp="2019-12-05T10:55:14 IST" time="150.946" errors="0">
  <testcase name="TC2" time="23.073" classname="com.pulse.Test.ValidLogin1">
    <failure type="java.lang.AssertionError" message="expected [Au Register Forms by Colorlib] but found [Yahoo India | News, Finance, Cricket, Lifestyle and Entertainment]">
      <![CDATA[java.lang.AssertionError: expected [Au Register Forms by Colorlib] but found [Yahoo India | News, Finance, Cricket, Lifestyle and Entertainment]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.pulse.Test.ValidLogin1.TC2(ValidLogin1.java:374)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase name="TC1" time="26.241" classname="com.pulse.Test.ValidLogin1"/>
  <testcase name="TC1" time="25.040" classname="com.pulse.Test.ValidLogin1"/>
  <testcase name="TC1" time="25.779" classname="com.pulse.Test.ValidLogin1"/>
  <testcase name="TC1" time="25.665" classname="com.pulse.Test.ValidLogin1"/>
  <testcase name="TC1" time="25.148" classname="com.pulse.Test.ValidLogin1"/>
</testsuite> <!-- com.pulse.Test.ValidLogin1 -->
